[project]
name = "ctc-risk-loan-analysis"
version = "0.1.0"
description = "Scripts for CTC risk innovation case study (cleanup and analytics)"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.2",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
]
